import React from 'react'

export const metadata = {
    title: "CrozyTech - Detail Project",
    description: "Generated by create next app",
};

export default function layout({ children }) {
    return (
        <main className='mx-4 mt-10 lg:mx-24'>
            {children}
        </main>
    )
}
